service: lambda-graphql
provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello

  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get
